# Generated by Django 4.1 on 2022-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
