# Generated by Django 4.1 on 2022-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('frigobar', models.ManyToManyField(to='itens.itens_frigobar')),
                ('itens_quarto', models.ManyToManyField(to='itens.itens_quarto')),
            ],
        ),
    ]
